# Starter pipeline

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: './Backend/Offensive_service'
  displayName: 'Build Offensive Service'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: './Backend/API_service'
  displayName: 'Build API'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: './Backend/Sentiment_service'
  displayName: 'Build Sentiment Service'

- task: DockerInstaller@0
  inputs:
    dockerVersion: '17.09.0-ce'

- task: Docker@2
  inputs:
    containerRegistry: 'Ki Sung''s DockerHub Registry'
    repository: 'ksnonsteal/my-webserver'
    command: 'buildAndPush'
    Dockerfile: './FrontEnd/Dockerfile'
    buildContext: './FrontEnd/'
  displayName: 'Build web app in web server image container and publish'

# - task: NodeTool@0
#   inputs:
#     versionSpec: '14.16.0'
#   displayName: 'Install Node.js'

# - script: |
#     echo "Installing npm dependencies"
#     ls
#     cd ./FrontEnd
#     npm i
#   displayName: 'npm install'

# - script: |
#     echo "Building web app with npm"
#     ls
#     cd ./FrontEnd
#     npm run build
#   displayName: 'npm build'

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloudCI'
    organization: 'soaprojectss1'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'soaprojectsS1_Proyecto-1-SOA'
    cliProjectName: 'Proyecto 1 SOA'
    cliSources: '.'
- task: SonarCloudAnalyze@1
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'