# Starter pipeline

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo "Building the Web API"
    cd ./Backend/API_service
    dotnet build
  displayName: 'dotnet build'

- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    echo "Building the Web App"
    cd ./FrontEnd
    npm i
    npm run build
  displayName: 'npm install and build'

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloudCI'
    organization: 'soaprojectss1'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'soaprojectsS1_Proyecto-1-SOA'
    cliProjectName: 'Proyecto 1 SOA'
    cliSources: '.'
- task: SonarCloudAnalyze@1
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'