# Starter pipeline

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

# - script: |
#     echo "Building the Web API"
#     cd ./Backend/API_service
#     dotnet build
#   displayName: 'dotnet build'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: './Backend/Offensive_service'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: './Backend/API_service'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: './Backend/Sentiment_service'

- task: NodeTool@0
  inputs:
    versionSpec: '14.16.0'
  displayName: 'Install Node.js'

- script: |
    echo "Installing npm dependencies"
    ls
    cd ./FrontEnd
    npm i
  displayName: 'npm install'

- script: |
    echo "Building web app with npm"
    ls
    cd ./FrontEnd
    npm run build
  displayName: 'npm build'

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloudCI'
    organization: 'soaprojectss1'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'soaprojectsS1_Proyecto-1-SOA'
    cliProjectName: 'Proyecto 1 SOA'
    cliSources: '.'
- task: SonarCloudAnalyze@1
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'