apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      # WEB SOCKET SERVER
      - name: my-websocket
        image: ksnonsteal/my-websocketserver:latest
        ports:
        - containerPort: 8000
      # WEB SERVER
      - name: my-webserver
        image: ksnonsteal/my-webserver:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - name: webapp
      port: 80
      targetPort: 80
      protocol: TCP
      # nodePort: 31180